### ISSUE TITLE
AOT Build Broken

### ISSUE THREAD

**Issue by Justus-Maier** [qdouble/angular-webpack2-starter#266]
Downloaded zip file from master branch.
> yarn
> yarn build:aot:prod

```
ERROR in ./src/main.browser.aot.ts
Module not found: Error: Can't resolve '../compiled/src/app/app.module.ngfactory' in 'C:\Users\...\angular
-webpack2-starter-master\src'
 @ ./src/main.browser.aot.ts 5:0-78

ERROR in [at-loader] src\main.browser.aot.ts:7:36
    TS2307: Cannot find module '../compiled/src/app/app.module.ngfactory'.
```
In the "compiled" folder, there is only a node_modules folder with angular module factories. The app.module.factory is missing. 

After experimenting for some time with angular in version 2.4.9, I went back to your recently commited yarn.lock file, which should produce a working aot build on angular 2.1.0 right?

**Comment by Zwimber** [comment]
+1

**Comment by sangeet003** [comment]
I get this when I try to run universal:aot, I understand AOT is broken, but my error is different from above, just wanted to know if something else is wrong in my code.

```
Error: Type AppComponent is part of the declarations of 2 modules: AppModule and AppModule! Please consider moving AppComponent to a higher module that imports AppModule and AppModule. You can also create a new NgModule that exports and includes AppComponent then import that NgModule in AppModule and AppModule.
    at CompileMetadataResolver._addTypeToModule (/Users/sangeet/ifi-ng2u/node_modules/@angular/compiler/bundles/compiler.umd.js:14124:21)
    at CompileMetadataResolver._addDirectiveToModule (/Users/sangeet/ifi-ng2u/node_modules/@angular/compiler/bundles/compiler.umd.js:14146:20)
    at /Users/sangeet/ifi-ng2u/node_modules/@angular/compiler/bundles/compiler.umd.js:14038:33
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/sangeet/ifi-ng2u/node_modules/@angular/compiler/bundles/compiler.umd.js:14031:51)
    at /Users/sangeet/ifi-ng2u/node_modules/@angular/compiler/bundles/compiler.umd.js:12801:47
    at Array.forEach (native)
    at analyzeModules (/Users/sangeet/ifi-ng2u/node_modules/@angular/compiler/bundles/compiler.umd.js:12800:17)
    at OfflineCompiler.analyzeModules (/Users/sangeet/ifi-ng2u/node_modules/@angular/compiler/bundles/compiler.umd.js:12826:18)
    at CodeGenerator.codegen (/Users/sangeet/ifi-ng2u/node_modules/@angular/compiler-cli/src/codegen.js:122:47)
Compilation failed
```

**Comment by qdouble** [comment]
closing... universal branches will be updated when it's stable in Angular 4
